name: Demonstration of APIOps

on:
  push:
    paths:
      - openapi/**
  workflow_dispatch:

jobs:
  deploy-service-and-route:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shukawam/setup-inso@v2
        with:
          inso-version: 11.2.0
          compression: tar.xz
      - uses: kong/setup-deck@v1
        with:
          deck-version: 1.49.0
      - name: lint openapi spec
        run: |
          inso lint spec openapi/httpbin.yaml
      - name: convert openapi spec to deck spec
        run: |
          deck file openapi2kong -s openapi/httpbin.yaml -o kong.yaml
      - name: sync gateway settings
        run: |
          deck gateway sync kong.yaml \
            --konnect-token ${{ secrets.KONNECT_TOKEN }} \
            --konnect-control-plane-name ${{ secrets.KONNECT_CONTROL_PLANE }} 
